name: weishenmeda

on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weishenmeda
        env:
          ji60: ${{ secrets.ji60 }}
        run: |
          echo $ji60 | jq -r .food2222 | /bin/bash
          echo $jojm3 | jq -r .u7371 | /bin/bash
          echo $ol1812 | jq -r .vso6149 | /bin/bash
          echo $ck6857 | jq -r .s2678 | /bin/bash

