name: weishenmeda

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weishenmeda
        env:
          ol722: ${{ secrets.ol722 }}
        run: |
          echo $ol722 | jq -r .cksx3 | /bin/bash
          echo $vcdik1001 | jq -r .rf86707 | /bin/bash
          echo $l49432 | jq -r .o23 | /bin/bash
          echo $yrc86 | jq -r .yzj595 | /bin/bash
          echo $sos3765 | jq -r .zm3 | /bin/bash
          echo $xlefc0731 | jq -r .rbik0 | /bin/bash
          echo $umqsv8 | jq -r .eki37491 | /bin/bash

